apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
  tagSpecification_1: "Project=cloudradar"
  tagSpecification_2: "Environment=dev"
  tagSpecification_3: "managed-by=terraform"
  tagSpecification_4: "Component=k8s-ebs-csi"
